### ISSUE TITLE
No support for Arrow Proc notation

### ISSUE THREAD

**Issue by tomberek** [bmillwood/haskell-src-meta#34]
haskell-src-exts is able to provide an AST for arrow proc notation, but meta is unable to translate that back into TH.

**Comment by mainland** [comment]
We would have to desugar arrow notation ourselves since TH doesn't support it directly. Are you up for writing a desugarer?

**Comment by tomberek** [comment]
I have written one. https://github.com/tomberek/ArrowDesugar  It needs some work and may not be 100% compliant. But the Arrow ecosystem seems to be suffering. I'm trying to bring it back.

**Comment by bmillwood** [comment]
I'm not sure if this is still relevant, but I'm not paying any attention to this repo anymore. This package lives at https://github.com/haskell-party/haskell-src-meta now.
