### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by bgamari** [bmillwood/haskell-src-meta#35]
The current release on Hackage is broken with GHC 7.10.

**Comment by bmillwood** [comment]
I can't get the GHC release candidate working for me at the moment (too little disk space!) so this will wait untili I can. Shouldn't be too hard.

**Comment by taladar** [comment]
The current released version 0.6.0.8 compiles if you merely relax the constraints for base and template-haskell

diff -ur original/haskell-src-meta-0.6.0.8/haskell-src-meta.cabal patched/haskell-src-meta-0.6.0.8/haskell-src-meta.cabal
--- original/haskell-src-meta-0.6.0.8/haskell-src-meta.cabal	2015-03-27 12:50:38.981127336 +0100
+++ patched/haskell-src-meta-0.6.0.8/haskell-src-meta.cabal	2015-03-27 12:55:40.511219964 +0100
@@ -19,14 +19,14 @@
 extra-source-files: ChangeLog README examples/*.hs
 
 library
-  build-depends:   base >= 4.2 && < 4.8,
+  build-depends:   base >= 4.2 && < 4.9,
                    haskell-src-exts == 1.16.*,
                    pretty >= 1.0 && < 1.2,
                    syb >= 0.1 && < 0.5,
                    th-orphans >= 0.5 && < 0.12
 
   if impl(ghc >= 7.4)
-    Build-depends: template-haskell >= 2.7 && < 2.10
+    Build-depends: template-haskell >= 2.7 && < 2.11
   else
     Build-depends: template-haskell >= 2.4 && < 2.7,
                    uniplate >= 1.3 && < 1.7

**Comment by taladar** [comment]
No, sorry, my mistake, I think I was a bit hasty in my last post...it seems there are some other compile errors.

**Comment by ddssff** [comment]
My fork (https://github.com/ddssff/haskell-src-meta) has a travis configuration that tests the build with ghc-7.4, 7.6, 7.8, 7.10, and head (results here: https://travis-ci.org/ddssff/haskell-src-meta).  Pull #41 adds this configuration.

**Comment by Athas** [comment]
I too support releasing a new version.  (This is also holding up `language-c-quote`, which has `haskell-src-meta` as a dependency.)  ddssff's pull request looks really sane from what I can see.

For what it's worth, the version of `haskell-src-meta` currently in Git works on GHC 7.10.1 for me.

**Comment by FranklinChen** [comment]
This is holding up IHaskell for GHC 7.10.1 also.

**Comment by luite** [comment]
+1, it's also a GHCJS dependency (but not for too much longer)

**Comment by bmillwood** [comment]
0.6.0.9 released.
