### ISSUE TITLE
Doesn't work with GHC 7.10

### ISSUE THREAD

**Issue by bos** [bmillwood/haskell-src-meta#42]
The dependency on base causes configuration to fail. I haven't checked to see what happens if it's widened.

**Comment by gibiansky** [comment]
Just ran into this as well [here](https://github.com/gibiansky/IHaskell/issues/464)! +1

**Comment by FranklinChen** [comment]
I already mentioned the holdup for IHaskell here: https://github.com/bmillwood/haskell-src-meta/issues/35

**Comment by ddssff** [comment]
This seems to have become a pretty crucial package.

**Comment by ddssff** [comment]
Isn't 7.10 using base-4.8?  I see base<4.9 in the cabal file.

**Comment by FranklinChen** [comment]
That change for `base` just hasn't been put into an actual release for Hackage yet.

**Comment by gibiansky** [comment]
@bmillwood Ping. Any chance of making a release on Hackage?

**Comment by angerman** [comment]
This is also blocking language-c-quote, from being updated to 7.10. https://github.com/mainland/language-c-quote/pull/47

**Comment by bmillwood** [comment]
Sorry for dragging my feet on this for a while. I had issues installing GHC 7.10.

In any case, not only is it done in 0.6.0.9, but I've added a second maintainer to reduce the chances of delay in future. I'm happy to add more, as well.
