### ISSUE TITLE
dependency upper bound for th-orphans

### ISSUE THREAD

**Issue by leepike** [bmillwood/haskell-src-meta#50]
`haskell-src-meta` currently has an upper bound of `<0.13`. But `th-orphans` was recently upgraded to `0.13`; in particular, the new release I believe fixes the problem documented [here](https://github.com/mgsloan/th-orphans/pull/25), making `th-orphans-0.12.2` incompatible with [nats-1.1](http://hackage.haskell.org/package/nats), the latest.

Can the `<0.13` constraint be relaxed (and fixed on Hackage)?

Thanks.

**Comment by zilinc** [comment]
Please. +1

**Comment by mainland** [comment]
Done.
