### ISSUE TITLE
Support haskell-src-exts-1.18.0

### ISSUE THREAD

**Issue by ddssff** [bmillwood/haskell-src-meta#57]
This new release of haskell-src-exts drops the simplified AST, so a lot of changes to haskell-src-meta are required.

**Comment by bmillwood** [comment]
Oh gosh, really? I hope they're at least relatively straightforward...

It's been quite a while since I've done a lot of work on haskell-src-meta and that doesn't look likely to change in the near future, so I think this one is going to need a sufficiently enthusiastic volunteer.

**Comment by ddssff** [comment]
I plan to do it at some point - could be a few weeks from now.

**Comment by tolysz** [comment]
There is [`haskell-src-exts-simple`](https://github.com/int-e/haskell-src-exts-simple) which possibly might ease the process...

**Comment by gbaz** [comment]
Any progress here? perhaps @mainland would be interested in helping too?

**Comment by ddssff** [comment]
I've made some progress here:

    https://github.com/ddssff/haskell-src-meta
    https://travis-ci.org/ddssff/haskell-src-meta/builds/161485412

But there are some cases in Translate.hs that need to be filled in - I have undefined in there now.

**Comment by tolysz** [comment]
Maybe we should drop anything bellow HSE < 1.18? as the cabal says so? And drop CPP for it.

**Comment by ddssff** [comment]
That would be great, and it looks like the test cases for old ghcs should build with 1.18.2 once everything gets straightened out.  But we'll still need CPP for different versions of template haskell.

**Comment by tolysz** [comment]
I think we should have to keep compatibility for a couple of TH versions but the question is how far back. We do not need anything bellow what HSE supports anyway.
But I would drop all CPP for HSE ;) (or keep it but remove cabal constraints).

**Comment by ddssff** [comment]
Please test these patches:  #58

**Comment by mainland** [comment]
1.18 is now supported in 0.7.0.

**Comment by ddssff** [comment]
Please see new pull request #59 to restore full support for haskell-src-exts-1.17.
