### ISSUE TITLE
Incorrect typing on class methods

### ISSUE THREAD

**Issue by Miltnoid** [bmillwood/haskell-src-meta#74]
Consider the following code:

`parseDecs "class MyClass a where mymethod :: a -> bool"`

This returns
`([ClassD [] MyClass [PlainTV a] [] [SigD my_method (ForallT [PlainTV a,PlainTV bool] [] (AppT (AppT ArrowT (VarT a)) (VarT bool)))]])`
instead of the expected `([ClassD [] MyClass [PlainTV a] [] [SigD my_method (AppT (AppT ArrowT (VarT a)) (VarT bool))]])`

I expect fixForAll is unnecessary, but if it is necessary, it should be given context information.

**Comment by JonasDuregard** [comment]
Does anyone know why fixForAll was added?
I added a test case for this in 595d900583956f6861667361653d73acddbf7207. Any attempt to restore whatever fixForAll was doing should pass that test.
