### ISSUE TITLE
Bump testsuite dependencies as well

### ISSUE THREAD

**Issue by neongreen** [bmillwood/haskell-src-meta#84]
@JonasDuregard Thanks for bumping `base` and `template-haskell`! Unfortunately, the testsuite still requires base<4.12 – can you bump it as well?

**Comment by neongreen** [comment]
(I'm only talking about Hackage revisions, in the repo itself everything is alright)

**Comment by JonasDuregard** [comment]
Done (for 0.8.0.3).
