### ISSUE TITLE
Fails to build with haskell-src-exts 1.21.0.

### ISSUE THREAD

**Issue by galenhuntington** [bmillwood/haskell-src-meta#85]
The commit https://github.com/haskell-suite/haskell-src-exts/commit/cc3188726c3d4ebd30a27d036c812ddd47d0d9fb replaced the `data Kind l` declaration, making instead `Kind` a synonym for `Type`.  As a result, `Language/Haskell/Meta/Syntax/Translate.hs` fails to compile with the current `haskell-src-exts`, starting at this instance declaration: https://github.com/bmillwood/haskell-src-meta/blob/8bfa70a501ed048298ecf992f613b3237631c98a/src/Language/Haskell/Meta/Syntax/Translate.hs#L317

This stuff is a bit over my head, so I'm not sure how to fix it.  Maybe this instance is no longer needed at all?

**Comment by galenhuntington** [comment]
I encountered this because I had to build a downstream package with `--allow-newer`, so the `< 1.21` bound didn't apply during installation.  So, most people won't run into this conflict immediately, but presumably the code will need to be updated eventually.

**Comment by DanBurton** [comment]
Bump. Would appreciate if haskell-src-meta could upgrade to be compatible with the new haskell-src-exts.

**Comment by galenhuntington** [comment]
I submitted a proposed solution in #86.

**Comment by bmillwood** [comment]
archiving this repo (and believe this has been fixed in forks)
